# Generated by Django 4.2 on 2023-05-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "bio",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "payment_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online", "Digital Payments"),
                            ("offline", "Cash Payments"),
                            ("all", "Both Digital and Cash Payments"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "tax_identification_number",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "business_email",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
